# Generated by Django 5.2.5 on 2025-09-22 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_atractivo', models.CharField(max_length=100)),
                ('calificacion_estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('descripcion_atractivo', models.TextField()),
                ('latitud_atractivo', models.FloatField()),
                ('longitud_atractivo', models.FloatField()),
                ('foto_atractivo', models.ImageField(blank=True, null=True, upload_to='atractivos/')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('patente_bus', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numero_unidad', models.IntegerField()),
                ('fecha_compra', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('personas', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_interes', models.DateField(blank=True, null=True)),
                ('recorrido_interes', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('respondida', models.BooleanField(default=False)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion_estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion_estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parada', models.CharField(max_length=100)),
                ('direccion_parada', models.CharField(max_length=255)),
                ('descripcion_parada', models.TextField()),
                ('foto_parada', models.ImageField(blank=True, null=True, upload_to='paradas/')),
                ('latitud_parada', models.FloatField()),
                ('longitud_parada', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_recorrido', models.CharField(max_length=50)),
                ('duracion_aproximada_recorrido', models.TimeField()),
                ('descripcion_recorrido', models.TextField()),
                ('foto_recorrido', models.ImageField(blank=True, null=True, upload_to='recorridos/')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chofer', models.CharField(max_length=100)),
                ('apellido_chofer', models.CharField(max_length=100)),
                ('legajo_chofer', models.CharField(max_length=20, unique=True)),
                ('dni_chofer', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBusHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_estado', models.DateTimeField()),
                ('estado_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.estadobus')),
                ('patente_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.bus')),
            ],
            options={
                'verbose_name_plural': 'EstadoBusHistorial',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('hora_inicio_programada', models.TimeField()),
                ('fecha_hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('demora_inicio_minutos', models.IntegerField(blank=True, null=True)),
                ('duracion_minutos_real', models.IntegerField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.chofer')),
                ('patente_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.bus')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('timestamp_ubicacion', models.DateTimeField()),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busturistico.viaje')),
            ],
            options={
                'verbose_name_plural': 'UbicacionColectivos',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio_estado', models.DateTimeField()),
                ('estado_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.estadoviaje')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.viaje')),
            ],
            options={
                'verbose_name_plural': 'HistorialEstadoViajes',
            },
        ),
        migrations.CreateModel(
            name='ParadaAtractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atractivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.atractivo')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.parada')),
            ],
            options={
                'verbose_name_plural': 'ParadaAtractivos',
                'unique_together': {('parada', 'atractivo')},
            },
        ),
        migrations.CreateModel(
            name='RecorridoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridoparadas', to='busturistico.parada')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridoparadas', to='busturistico.recorrido')),
            ],
            options={
                'verbose_name_plural': 'RecorridoParadas',
                'unique_together': {('recorrido', 'parada', 'orden')},
            },
        ),
    ]
