# Generated by Django 5.2.1 on 2025-07-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_atractivo', models.CharField(max_length=100)),
                ('calificacion_estrellas', models.IntegerField(max_length=5)),
                ('descripcion_atractivo', models.TextField()),
                ('latitud_atractivo', models.FloatField()),
                ('longitud_atractivo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('patente_bus', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numero_unidad', models.IntegerField()),
                ('fecha_compra', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_chofer', models.CharField(max_length=100)),
                ('apellido_chofer', models.CharField(max_length=100)),
                ('legajo_chofer', models.CharField(max_length=20)),
                ('dni_chofer', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion_estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion_estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parada', models.CharField(max_length=100)),
                ('direccion_parada', models.CharField(max_length=255)),
                ('descripcion_parada', models.TextField()),
                ('link_foto_parada', models.URLField()),
                ('latitud_parada', models.FloatField()),
                ('longitud_parada', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_recorrido', models.CharField(max_length=50)),
                ('duracion_aproximada_recorrido', models.TimeField()),
                ('descripcion_recorrido', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('numero_paradas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoBusHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_estado', models.DateTimeField()),
                ('estado_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.estadobus')),
                ('patente_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.bus')),
            ],
        ),
        migrations.CreateModel(
            name='ParadaAtractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atractivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.atractivo')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.parada')),
            ],
        ),
        migrations.CreateModel(
            name='RecorridoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.parada')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('hora_inicio_programada', models.TimeField()),
                ('fecha_hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('demora_inicio_minutos', models.IntegerField(blank=True, null=True)),
                ('duracion_minutos_real', models.IntegerField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.chofer')),
                ('estado_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.estadoviaje')),
                ('patente_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.bus')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.recorrido')),
            ],
        ),
    ]
