# Generated by Django 5.2.5 on 2025-09-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('24h', 'Pase 24 horas'), ('48h', 'Pase 48 horas'), ('familiar', 'Pase Familiar')], max_length=20)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('inicio_titulo', 'Título sección inicio'), ('inicio_descripcion', 'Descripción sección inicio'), ('precios_titulo', 'Título sección precios')], max_length=50)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('pt', 'Português')], max_length=5)),
                ('texto', models.TextField()),
            ],
            options={
                'unique_together': {('clave', 'idioma')},
            },
        ),
    ]
