# Generated by Django 5.2.5 on 2025-08-11 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='link_foto_parada',
        ),
        migrations.AddField(
            model_name='atractivo',
            name='foto_atractivo',
            field=models.ImageField(blank=True, null=True, upload_to='atractivos/'),
        ),
        migrations.AddField(
            model_name='parada',
            name='foto_parada',
            field=models.ImageField(blank=True, null=True, upload_to='paradas/'),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='foto_recorrido',
            field=models.ImageField(blank=True, null=True, upload_to='recorridos/'),
        ),
        migrations.AlterField(
            model_name='atractivo',
            name='calificacion_estrellas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='paradaatractivo',
            unique_together={('parada', 'atractivo')},
        ),
        migrations.AlterUniqueTogether(
            name='recorridoparada',
            unique_together={('recorrido', 'parada', 'orden')},
        ),
        migrations.CreateModel(
            name='HistorialEstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio_estado', models.DateTimeField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.estadoviaje')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busturistico.parada')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionColectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('timestamp_ubicacion', models.DateTimeField()),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busturistico.parada')),
            ],
        ),
        migrations.AddField(
            model_name='estadoviaje',
            name='ubicacion_colectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busturistico.ubicacioncolectivo'),
        ),
    ]
