# Generated by Django 5.2.5 on 2025-09-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_programada',
            field=models.DateField(),
        ),
    ]
