# Generated by Django 5.2.5 on 2025-08-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0002_remove_parada_link_foto_parada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialestadoviaje',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='historialestadoviaje',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='historialestadoviaje',
            name='parada',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='numero_paradas',
        ),
        migrations.RemoveField(
            model_name='ubicacioncolectivo',
            name='parada',
        ),
        migrations.AddField(
            model_name='viaje',
            name='ubicacion_colectivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='busturistico.ubicacioncolectivo'),
        ),
    ]
