# Generated by Django 5.2.5 on 2025-10-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0002_precio_traduccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traduccion',
            options={'verbose_name_plural': 'Traducciones'},
        ),
        migrations.AlterField(
            model_name='traduccion',
            name='clave',
            field=models.CharField(choices=[('inicio_titulo', 'Título sección inicio'), ('inicio_descripcion', 'Descripción sección inicio'), ('precios_titulo', 'Título sección precios'), ('precios_subtitulo', 'Subtítulo sección precios')], max_length=50),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_personas', models.IntegerField(default=1)),
                ('fecha_reserva', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.precio')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busturistico.recorrido')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
