# Generated by Django 5.2.5 on 2025-08-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0003_remove_historialestadoviaje_latitud_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadobushistorial',
            options={'verbose_name_plural': 'EstadoBusHistorial'},
        ),
        migrations.AlterModelOptions(
            name='historialestadoviaje',
            options={'verbose_name_plural': 'HistorialEstadoViajes'},
        ),
        migrations.AlterModelOptions(
            name='paradaatractivo',
            options={'verbose_name_plural': 'ParadaAtractivos'},
        ),
        migrations.AlterModelOptions(
            name='recorridoparada',
            options={'verbose_name_plural': 'RecorridoParadas'},
        ),
        migrations.AlterModelOptions(
            name='ubicacioncolectivo',
            options={'verbose_name_plural': 'UbicacionColectivos'},
        ),
        migrations.RemoveField(
            model_name='estadoviaje',
            name='ubicacion_colectivo',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='estado_viaje',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='ubicacion_colectivo',
        ),
        migrations.AddField(
            model_name='ubicacioncolectivo',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busturistico.viaje'),
        ),
    ]
