# Generated by Django 5.2.5 on 2025-10-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0002_alter_viaje_fecha_programada'),
        ('busturistico', '0003_alter_traduccion_options_alter_traduccion_clave_and_more'),
    ]

    operations = [
    ]
