# Generated by Django 5.2.5 on 2025-10-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0004_merge_20251023_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
