# Generated by Django 5.2.5 on 2025-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0005_alter_atractivo_foto_atractivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractivo',
            name='foto_atractivo',
            field=models.ImageField(blank=True, null=True, upload_to='atractivos/'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='foto_parada',
            field=models.ImageField(blank=True, null=True, upload_to='paradas/'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='foto_recorrido',
            field=models.ImageField(blank=True, null=True, upload_to='recorridos/'),
        ),
    ]
