# Generated by Django 5.2.5 on 2025-10-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0005_recorrido_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pase',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='recorrido',
        ),
        migrations.DeleteModel(
            name='Traduccion',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='activo',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
