# Generated by Django 5.2.5 on 2025-08-18 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0006_alter_atractivo_foto_atractivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atractivo',
            name='foto_atractivo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/atractivos/'),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='legajo_chofer',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parada',
            name='foto_parada',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/paradas/'),
        ),
        migrations.AlterField(
            model_name='recorrido',
            name='foto_recorrido',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/recorridos/'),
        ),
    ]
