# Generated by Django 5.2.5 on 2025-10-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0006_remove_reserva_pase_remove_reserva_recorrido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
