# Generated by Django 5.2.5 on 2025-10-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0007_delete_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('24h', 'Pase 24 horas'), ('48h', 'Pase 48 horas'), ('familiar', 'Pase Familiar')], max_length=20)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
