# Generated by Django 5.2.5 on 2025-08-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0007_alter_atractivo_foto_atractivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorridoparada',
            name='parada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridoparadas', to='busturistico.parada'),
        ),
        migrations.AlterField(
            model_name='recorridoparada',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridoparadas', to='busturistico.recorrido'),
        ),
    ]
