# Generated by Django 5.2.5 on 2025-09-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busturistico', '0008_alter_atractivo_foto_atractivo_and_more'),
        ('busturistico', '0008_alter_recorridoparada_parada_and_more'),
    ]

    operations = [
    ]
