erDiagram
    %% Diagrama de Entidad-Relación para el sistema de recorridos de buses
    Recorrido ||--o{ Recorrido_Parada : tiene_paradas
    Parada ||--o{ Recorrido_Parada : esta_en
    Parada ||--o{ Parada_Atractivo : tiene_atractivos
    Atractivo ||--o{ Parada_Atractivo : es_atractivo_de

    Bus_Chofer }|--o| Bus : es_asignado_a
    Bus_Chofer }|--o| Chofer : es_asignado_a
    Bus_Chofer ||--|{ Viaje : realiza

    Bus ||--o{ Estado_Bus : tiene_estado
    Viaje }|--|| Recorrido : asociado_a

    Recorrido {
        int id_recorrido PK
        str color_recorrido
        time duracion_aproximada_recorrido
        str descripcion_recorrido
    }

    Recorrido_Parada {
        int id_recorrido_parada PK
        int id_recorrido FK
        int id_parada FK
        int orden
    }

    Parada {
        int id_parada PK
        str nombre_parada
        str direccion_parada
        str descripcion_parada
        str link_foto_parada
    }

    Parada_Atractivo {
        int id_parada_atractivo PK
        int id_parada FK
        int id_atractivo FK
    }

    Atractivo {
        int id_atractivo PK
        str nombre_atractivo
        int calificacion_estrellas
        str descripcion_atractivo
    }

    Bus {
        str patente_bus PK
        int numero_unidad
        datetime fecha_compra
        int id_estado_bus FK
    }

    Estado_Bus {
        int id_estado_bus PK
        str nombre_estado
        str descripcion_estado
    }

    Chofer {
        int id_chofer PK
        str nombre_chofer
        str apellido_chofer
        str legajo_chofer
    }

    Bus_Chofer {
        int id_asignacion PK
        str patente_bus FK
        int id_chofer FK
        datetime fecha_programada
        time hora_inicio_programada
        bool es_activo
    }

    Viaje {
        int numero_viaje PK
        datetime fecha_hora_inicio_real
        datetime fecha_hora_fin_real
        int duracion_minutos_real
        int id_recorrido FK
        int id_asignacion_bus_chofer FK
        int demora_inicio_minutos
    }
